# Generated by Django 2.1.7 on 2019-02-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_auto_20190226_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
