# Generated by Django 2.1.7 on 2019-02-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['album_title']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['song_title']},
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
