# Generated by Django 2.1.7 on 2019-02-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190221_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
