# Generated by Django 2.1.7 on 2019-02-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190221_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_url',
            field=models.CharField(default='NO url', max_length=500),
            preserve_default=False,
        ),
    ]
