# Generated by Django 2.1.7 on 2019-02-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
    ]
