# Generated by Django 2.1.7 on 2019-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='file_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
