# Generated by Django 2.1.7 on 2019-02-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_album_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_type',
        ),
    ]
