# Generated by Django 2.1.7 on 2019-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_delete_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, default='No Lyric Found', null=True),
        ),
    ]
